### PR TITLE
[WIP] Update Ebot for CS2

### PR DESCRIPTION
**Pull request by Iwhite67**
Change logaddress_add -> logaddress_add_http
logaddress_del -> logaddress_delall_http

Error when ebot want to connect to CS2
https://github.com/deStrO/eBot-CSGO/blob/39bfe71938df245373ce3b3448b5014ae39c8cc3/src/eBot/Match/Match.php#L167

### CODE REVIEW

**Comment by deStrO** [comment]
I'm planning an update for later this week :)

**Comment by Iwhite67** [comment]
Hello

Je te drop ceci si jamais

for anyone struggling to use rcon externally - in my case I tried to use a library that works just fine in CS:GO (python-valve) but didnt work correctly in CS2, was getting the autokick is disabled thing

I tried another python library and it works correctly
https://github.com/conqp/rcon

also dont forget to add -usercon in launch params

**Comment by chevlor** [comment]
Hello lhwite67,

Aurais-tu déjà trouver un fix intégré à la version actuelle d'eBot avec cette nouvelle librairie ?

J'ai une LAN le week-end prochain, donc je serais volontiers preneur ^^.

Merci encore @deStrO de nous faciliter la vie en LAN !

**Comment by Iwhite67** [comment]
Hello, non car je ne me connais pas assez pour dev

**Comment by Flegma** [comment]
I've managed to get it to send commands from eBot to the server, but its not recieving any info from the server (example: !ready command). 

Anyone made full update to work?

**Comment by Iwhite67** [comment]
Have you change logaddress car ?

**Comment by deStrO** [comment]
I'm on it today, I'm changing the way how logs are handled as it's http only now :)
I'm adding a queue server to handle that case.

**Pull request closed without merging**
