### PR TITLE
Added some things

### PR DESCRIPTION
**Pull request by sqrtroot**
Added Knife only on knife round(stupid commit name)
Added custom chat prefix system
Changed some french things to english

### CODE REVIEW

**Comment by sqrtroot** [comment]
f*ck i shouldn't trust autoreplace xD

**Comment by mLgz0rn** [comment]
:D But do you have any idea of what's wrong with line 122?

**Comment by sqrtroot** [comment]
no i honestly don't know. in lines 64-73 of destr0's version of this file it's done the same way https://github.com/deStrO/eBot-CSGO/blob/074f3b36d5df1a2db9dc6247dd88add8a9be6dd8/src/eBot/Application/Application.php

**Comment by deStrO** [comment]
I already included those features in the next eBot version (4.0).

I won't merge it for now :)

**Comment by sqrtroot** [comment]
That's really neat, do you need people to beta test/help with development?

**Comment by deStrO** [comment]
A new version has been pushed, it won't be merged.

**Pull request closed without merging**
