### PR TITLE
Master

### PR DESCRIPTION
**Pull request by heew**
### .gitignore https://github.com/deStrO/eBot-CSGO/commit/bd8c8658df5b61ed5ad0e251c26487dc4642bc16, https://github.com/deStrO/eBot-CSGO/commit/47f52bea74068825376fd27f837d3ec352197cdb:

1. Added `config/config.ini` to .gitignore, renamed `config.ini` to `config.ini.smp`.
2. Added `demos/*.dem*` and `logs/*` to .gitignore to avoid demos/logs being tracked.

### Log entries https://github.com/deStrO/eBot-CSGO/commit/15455e3de889a79880ede606105702024fef330f, https://github.com/deStrO/eBot-CSGO/commit/6a295f636666d1fffe0ddde83d27adf5b18daa0b, https://github.com/deStrO/eBot-CSGO/commit/7d3547d0ff38136f9ff778882da12315cab750a2:
1. Translated French log entries to English.
2. Fixed Gramatical errors in say/log entires.

### Color formatting, say() and say_player() function https://github.com/deStrO/eBot-CSGO/commit/7d0e25beb733e9911d7abec322f33691dd063556, https://github.com/deStrO/eBot-CSGO/commit/196b2d7e5555316d7f6f85a4cd78f112bf5f27d0:
1. Added functionality for say() to support whole line color formatting, for example a line in red: `$this->say("text", "red");`.
2. Added new function `formatText("TEXT", "COLOR")` to handle color codes, replaced all `say()` entries to utilize these two new functionalities.
3. Added new function `say_player()` to handle csay_to_player plugin calls.

### Commands https://github.com/deStrO/eBot-CSGO/commit/34067195059512d377254165b4c3d88ede4302ab, https://github.com/deStrO/eBot-CSGO/commit/1b912bd1db5b938ca9beb5c748bd0cfc56020ed5, https://github.com/deStrO/eBot-CSGO/commit/00d4ab34842e158417da44ce5b798bd0033d4108:
1. Fixed typo with `!abort` command.
2. Added function `isCommand($message, $command);` which determines if user text is a valid command.
3. Cleaned up all logic in checking if user entered a command to utilize `isCommand()` calls.
4. All commands now support the prefixes `!` and `.`, they also ignore case sensitivity.
5. New command: `!fixwarmup` now executes warmup config in the event that the warmup config does not get executed (due to timeout or the like while map is loading) this command can only be used once per game.
6. New command: `!connect` which shares the `CONNECT <ip>; PASSWORD <pass>` string to this eBot instance. *TODO:* This should probably be changed to use `say_player()` instead of `say()` in the future when plugin csay is fixed.

###  config/config.ini.smp https://github.com/deStrO/eBot-CSGO/commit/42f6902e163525645d834d6d4048329eb6296e9a, https://github.com/deStrO/eBot-CSGO/commit/8407f0abecf4735e6c7f4747b927ecb5c92c0785:
1. Added maps `de_cbble` and `de_overpass`.

### pauseMatch() function https://github.com/deStrO/eBot-CSGO/commit/4c61f7e46d03c2cfa44cde16ef01f0e05a21a190, https://github.com/deStrO/eBot-CSGO/commit/15cfa5f627f22aa2dd5ef4aea4ac6d2bccba22cf:
1. Cleaned up code to be more readable, functionality is same.
2. Replaced duplicate code with new logic - still same functionality only easier to read.

### In-game configuration management https://github.com/deStrO/eBot-CSGO/commit/6c14b9b0cff5060dd1dbd6e0040727a287b2ef6a, https://github.com/deStrO/eBot-CSGO/commit/4b3ad4e9e91afbf23a04285193e0d46f8881de8b:
1. Added knife round config (no pistol or money upon knife round start and free armor).
2. Warmup now consists of max start money (60000) and free armor.
3. New functions `executeWarmupConfig()`, `undoWarmupConfig()`, `executeKnifeConfig()`, `undoKnifeConfig()` and `executeMatchConfig()` now handles all config, replaced all `$this->rcon->send(<CONFIG HERE>);` lines with usage of these functions.
4. Added new function `goLive($type)` which announces ingame that `$type` is live, shortened code in `startMatch()` by using this function - same functionality.
5. Added  Add `sv_rcon_whitelist_address` to construct function.

### Demos https://github.com/deStrO/eBot-CSGO/commit/c66f572639e263a45a9ae732ac03e90e6ddfe7af, https://github.com/deStrO/eBot-CSGO/commit/dff1e689cd42a4cb46a1994e1c90d25a4a855787:
1. Fixed automatic tv_record upon knife/match start.
2. Fixed a bug where tv_record would not start if `RECORD_METHOD` is `knifestart` and there was no knife round played.

### Status messages in sendRotateMessage() https://github.com/deStrO/eBot-CSGO/commit/0601f87448ca1ac73afd58c8a5f8eba266300855:
1. Cleaned up messages to better indicate what eBot is waiting for and actually show what commands are available.

### Damage report https://github.com/deStrO/eBot-CSGO/commit/38fdb03dddb1f4a64ab3a8825289dd6df122b37d, https://github.com/deStrO/eBot-CSGO/commit/406948fc803cd489cd6492c191159b47640cf2f8, https://github.com/deStrO/eBot-CSGO/commit/f4747fea24bc34b2e27ef46580ffc3378c237113, https://github.com/deStrO/eBot-CSGO/commit/f6d6e070c7b4051b3ab4058085ec3986d16d5709, https://github.com/deStrO/eBot-CSGO/commit/cab154de1edcf4d638622cb3d2c6b0817c2a9f36, https://github.com/deStrO/eBot-CSGO/commit/9648ea67b81cc11eed3bdb5f07151fe71494e427, https://github.com/deStrO/eBot-CSGO/commit/17ea5edce7094285940e4f14134beb882e8b60e1, https://github.com/deStrO/eBot-CSGO/commit/8bc0efdd3e67197c0dff879bb0f6958dbc345d51, https://github.com/deStrO/eBot-CSGO/commit/b5e2a76449ce35e397c1e3d41aee39cbae018a72:
1. eBot now is able to process attacked messages in the UDP logstream, for this I had to set `mp_logdetail 3` in `__construct()` for Match.php. This is done so that we can properly track players HP even in the event that team damage is done.
2. In order to properly track players HP we set all players HP to 100 in function `processRoundSpawn() `.
3. In the event that a player takes fall/world damage we set player HP to 0 in the function `processKill()`, this is unfortunately not logged so I can't handle it in any other way.
4. At the end of the round in function `processRoundScored()` we call `generateDamageReports()` to print damage reports to each player. This does not currently work because csay_to_player is not working as I mentioned in a tweet to @deStrO .

### CODE REVIEW

**Comment by KoSoVaR** [comment]
Really great additions & fixes.  Hopefully @deStrO merges.

Have you by chance been able to look at the match medic features - in particular src/eBot/Match/Match.php line 2596, 3160.  I haven't been able to figure out why but match medic is just broken.  It works intermittently but often times not.  Would this possibly be related to #4 under damage report with processRoundScored() ?  

I am sorry, I know this is not the right place to comment about this, but you seem to be the only active person working on this.

**Comment by heew** [comment]
@KoSoVaR Can you link me the line? https://github.com/heew/eBot-CSGO/blob/master/src/eBot/Match/Match.php.

**Comment by KoSoVaR** [comment]
Any logic with mp_backup*, 2707 on yours looks like where it gets the file to restore.  Basically there is a mechanism in which these log files are stored every round and should be restored in case of any issue.  Something is wrong in the way this logic currently works.  I don't know what, but it doesn't work well.  It's almost as if eBot is not using the native CSGO logging method, maybe @deStrO wrote his own or something.

Problem is I'm a consumer and not a contributor, I just don't have that skill set :(  I can try to help in any way shape or form that I can.. but actually writing anything won't come from this guy.

**Comment by heew** [comment]
@KoSoVaR I have not tested this myself, if it is not working it should not be too hard to fix; I suggest opening an issue for it :+1: . And yes it could be that it is already fixed, but not uploaded to git I don't know.

**Comment by KoSoVaR** [comment]
@heew I completely understand and I have.  https://github.com/deStrO/eBot-CSGO/issues/62

See @deStrO response

> I already saw that kind of issues before, sometimes a round is counted twice and it's un-fixeable for now in live.

When doing this completely manual we've never had a problem restoring matches like we've had with eBot.  I'm skeptical there isn't a fix since this is used in big tournaments.

**Comment by heew** [comment]
@KoSoVaR I see that now, problem is there seems to be no way to reproduce this error, or am I wrong? If you give me steps to reproduce I can maybe be of help. If its 100% reproducable it should be fixable IMO. I got the feeling from the issue that it happens at random.

**Comment by KoSoVaR** [comment]
@heew it's definitely intermittent but does happen often.

   1. start a competitive game (5v5)
   2. play a few rounds
   3. restore to previous round
   4. continue playing match
   5. restore again, I've seen the issue happen most when score is 8-7

Sometimes the restore won't work on the first try, usually it does when
troubleshooting (OF COURSE IT DOES!). However when I've had full games
running in a tournament and the score is 7-7 and a perhaps a power outage
happens and we need to restore the round back to 7-7 (this has happened
multiple times unfortunately at one of the tournaments I was assisting
with, they just couldn't figure out power) and it ends up not working.
When I can't restore a match to a specific score not only does it look
terrible on the organizers, players get super pissy.

Some symptoms you will notice:

   - money and guns are correct but teams are swapped
   - Sometimes you can restore and everyone's just dead and floating
   - Every restore guns keep piling up on the ground

Test cases:

   - server is force killed - you bring the server back up and all players
   connect. You then use the match restore option.
   - In the middle of a match a user disconnects (typical rule is you can
   restore the round if a kill hasn't occurred before a disconnect) and
   reconnects

If it helps I can add you on Google Hangouts/Steam and we can perhaps debug
together?

On a COMPLETE sidenote, perhaps adding a knife round customization in the
configure match section would help all of these folks who are releasing
"patches" to the knife round (full armor, time limit, no guns, no bomb)
might be helpful as well.

**Comment by heew** [comment]
@KoSoVaR Seems like this would be an issue where game server registers a new half is started and eBot correctly updates score, but I geuss there is a issue where after restore eBot does not alter its own score? I think something like that is worked on being fixed in these commented out lines that I found: https://github.com/heew/eBot-CSGO/blob/master/src/eBot/Match/Match.php#L2729. I am not sure why they are commented out, I would have to check further when I have time.

**Comment by MikkelDK** [comment]
Do you know why etc !help and !rules dont work? - CSay are installed and anything.

**Comment by heew** [comment]
@MikkelDK Because the csay_to_player function in the CSay plugin is broken. I have notified @deStrO about it on twitter. Because the source of the plugin is not public knowledge (AFAIK) only him can fix it.

**Comment by MikkelDK** [comment]
@heew - Daamn. - Are it's same with the other commands? Example: !status, !stats etc etc?

**Comment by heew** [comment]
@MikkelDK Yes.

**Comment by MikkelDK** [comment]
@heew Lets hope it will be fixed! :-) - I have tested your commands today with (fixwarmup/and connect) it work perfect! ;)

**Comment by Versatile-BFG** [comment]
a quick sm plugin can fix it though.

`#include <sourcemod>
#pragma semicolon 1

public Plugin myinfo = {
	name = "eBot csay fix",
	author = "Versatile BFG",
	description = "fix for ebot csay",
	version = "1.0",
	url = "http://www.sourcemod.net/"
};



public void OnPluginStart() {
//Temp work around for csay issue
	RegAdminCmd("csay_to_player", csay_to_player_fix, ADMFLAG_CUSTOM1, "Temp work around for csay issue");
}

public Action csay_to_player_fix(int client, int args) {

	if (args < 2) {
		return Plugin_Handled;	
	}	
	
	char uid[4];
	char message[192];
	GetCmdArg(1, uid, sizeof(uid));
	GetCmdArg(2, message, sizeof(message));
	
	int userid = StringToInt(uid);
	int target = GetClientOfUserId(userid);
	
	if (target == -1 || target == 0)
		return Plugin_Handled;
		
	PrintToChat(target, "%s", message);
	
	return Plugin_Handled;
}`

**Comment by MikkelDK** [comment]
@heew - Are its possible for you can update the match.php for the "fix" you have found? ;) since i dont wanna to "edit" on match.php ;)

**Comment by heew** [comment]
@MikkelDK I am not sure if that is a fix or not, to me it seems like a WIP and I think there is a reason for why it is commented out.

@Versatile-BFG Good stuff! I just tested and your workaround works, I also found I had a typo in the for loop with generateDamageReports so if any of you want to use this functionality make sure to get the newest version. Ideally the csay plugin should be updated to fix this instead of having another plugin to fix an issue with csay, but this will suffice for me until a permanent fix is issued by @deStrO.

**Comment by KoSoVaR** [comment]
@heew ever get any time to look in to match restore/medic?

**Comment by heew** [comment]
@KoSoVaR Unfortunately not, I have not had much free time lately.

**Comment by MikkelDK** [comment]
Do the Damage show work ? (also example:
"eBot: (0 / 0 hits) to (0 / 0 hits) from Alexi <green> (100 hp)." (where it's need to post/say/console on the ingame of server)

i can see it using: csay_to_player. so questions about it can be used with the "plugin upper from"

**Comment by Versatile-BFG** [comment]
Just got a tweet from deStrO saying he has access to the csay dev os. There should be an update to csay now or shortly.

**Comment by MikkelDK** [comment]
@Versatile-BFG nice nice! it's good news!!! ;)

**Comment by deStrO** [comment]
This is a nice pull request in fact.

Maybe try to do those points before I'll do a merge:
- Add a config to disable the damage printing
- Add a config to disable the "don't forget to record"

I'll make some test when you resolv those point and check for a merge.

**Comment by heew** [comment]
@deStrO Sorry for late reply I have been busy. I will add it.

**Comment by heew** [comment]
@deStrO Its added now, config options `REMIND_RECORD` which defaults to true and `DAMAGE_REPORT` which also defaults to true.

**Comment by deStrO** [comment]
Okay, I'll try your eBot today and review what you did on the code.

**Comment by deStrO** [comment]
The CSay plugin has been updated

**Comment by deStrO** [comment]
I tested what you did.

The damage report doesn't work it says 0 hit, I'll inspect your code :)

**Comment by heew** [comment]
@deStrO it should work, if your trying vs bots it does not work - damage done to / taken from bots does not registrer. You must test with another player. Remember it sets HP at round spawn.

**Comment by deStrO** [comment]
I found the issue, the messages.ini doesn't contain the Attacker message

**Comment by deStrO** [comment]
Please set your POV config to false too :)

**Comment by heew** [comment]
I dont understand was my messages.ini file not correct in my master branch? I can fix it soon im in a matchmaking game.

**Comment by MikkelDK** [comment]
Do the damage report works with (say) after new round? example from ESEA.

**Comment by heew** [comment]
@deStrO its updated now.. The messages.ini thing was it something with my PR?

**Comment by deStrO** [comment]
It seems not commited for the messages.ini

**Comment by heew** [comment]
Can you link me the file? I can't seem to find it which is weird.

**Comment by heew** [comment]
I have checked like this and I can't find any differences with my files from what is in git so thats strange:
`[root@script02:/usr/share/eBot-CSGO/src]# for F in $(find . -type f); do echo -en "$F:\t";  echo $(md5sum $F |awk '{print $1}'); echo -en "$F:\t"; echo $(md5sum /git/eBot-CSGO/src/$F |awk '{print $1}'); done |sort |uniq -c |grep -v '2 ./'`

**Comment by deStrO** [comment]
Don't worry, will update it :)

**Comment by KoSoVaR** [comment]
good work @heew 

@deStrO since you seem to be active on this thread :)  any ideas on the match medic / restore options?

**Comment by deStrO** [comment]
I'll have a look, but can you make a full post who describe the error please? :)

**Comment by MikkelDK** [comment]
The damage reports, do it works with "say" on the server?

**Comment by heew** [comment]
@MikkelDK What do you mean with "say"? I believe @deStrO has updated the csay plugin so it should work natively - although I have not had a chance to test it yet. If you have the old version of csay then just download the latest - see http://forum.esport-tools.net/d/18-csay-3-2-4-released for information.

**Comment by MikkelDK** [comment]
@heew -  it' works.
But i found new issue/bug.

- if i go on Backup System and load round 9
Server/CSay tell me to use: !continue

but it don't works.

**Comment by heew** [comment]
@MikkelDK Can you share with me the connection info to the server which you have issues on now? Just change password to something you dont care about and I will connect and see.

**Comment by MikkelDK** [comment]
@heew - sure: we're testing on: connect 37.187.8.197:27075 ;password war

**Comment by heew** [comment]
@MikkelDK thanks I have only less than 30 minutes before I must leave for work.

**Comment by MikkelDK** [comment]
@heew no problems. there is too issue with show damage:
Example if i damage you 108 - it' just show 100.

**Comment by heew** [comment]
@MikkelDK My PC crashed (happens a lot lately - I have ordered a new - not yet arrived), but as we found out it seems to be a issue with the backup/restore system that it does not track the state of the game (paused etc). Workaround for now would be to `!pause` and `!unpause`.

**Comment by MikkelDK** [comment]
@heew - Yeah i see! ;) thanks. - maybe i will try to look on the match.php and see what i can find.

**Comment by KoSoVaR** [comment]
@heew so the issues I was speaking of exist?  backup/restore system not
tracking correctly?

**Comment by heew** [comment]
@KoSoVaR I think there are issues with backup/restore system yes, but I have not had much time to look into it.

**Comment by stubbegianni** [comment]
@heew people would want to see the full damage they dealt (if over 100) so if they wallbang a door or similar they see how much that did exactly.

Nice work btw!

**Comment by heew** [comment]
@stubbegianni Thanks, I think it should become an option in config.ini. I think I will add this and some other things when I find time to do it.

**Comment by mrc4tt** [comment]
@heew I think it's rude to contact you again. :-)

Do you have any ideas about what happened to the damage print? As it no longer shows how much damage has been given/received.

It just shows 0.
Any ideas for a fix?

image

**Pull request merged**
